apps/contact/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'contact'
urlpatterns = [
    url(r'^add/$', views.AddView.as_view(), name='add_contact'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^', views.IndexView.as_view(), name='index'),
]

apps/front/urls.py
from django.conf.urls import url
from . import views

__author__ = 'snake'


urlpatterns = (
    url(r'^$', views.home, name='home'),
)

kevinleroyer/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from apps.front.views import error
from django.views.i18n import javascript_catalog
from .sitemaps import sitemaps
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('apps.custom_admin', 'apps.front', 'apps.user_profile', )
}

urlpatterns = [
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'), {
        'PROJECT_URI': settings.PROJECT_URI
    }),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^emails/', include('nixa_emails.urls')),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
    url(r'^', include('apps.front.urls')),
]

urlpatterns += i18n_patterns(
    url(r'^contacts/', include('apps.contact.urls')),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns.append(
        url(r'^error', error, name='error')
    )
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contact/models.py
from django.db import models
from django.conf import settings

class Contact(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    email = models.CharField(max_length=255, unique=True)
    phone = models.CharField(max_length=255)
    creation_date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.phone = "%s%s%s %s%s%s-%s%s%s%s" % tuple(self.phone)
        super(Contact, self).save(*args, **kwargs)

    def __str__(self):
        return self.firstname + ' ' + self.lastname

class Address(models.Model):

    AB, BC, MB, NB, NL, NS, ON, PE, QC, SK = range(10)
    PROVINCES = (
        (AB, 'Alberta'),
        (BC, 'British Columbia'),
        (MB, 'Manitoba'),
        (NB, 'New Brunswick'),
        (NL, 'Newfoundland and Labrador'),
        (NS, 'Nova Scotia'),
        (ON, 'Ontario'),
        (PE, 'Prince Edward Island'),
        (QC, 'Quebec'),
        (SK, 'Saskatchewan'),
    )

    contact = models.OneToOneField(Contact, on_delete=models.CASCADE)
    street_name = models.CharField(max_length=255)
    street_number = models.IntegerField()
    city = models.CharField(max_length=255)
    zip_code = models.CharField(max_length=10)
    province = models.IntegerField(choices=PROVINCES)

apps/contact/forms.py
from django.forms import ModelForm

from .models import Address, Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        exclude = ['user']

class AddressForm(ModelForm):
    class Meta:
        model = Address
        exclude = ['contact']

apps/contact/views.py
from django.views import generic
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from .models import Contact
from .forms import AddressForm, ContactForm

class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'contact/index.html'
    context_object_name = 'contact_list'

    def get_queryset(self):
        user = self.request.user
        return Contact.objects.filter(user=user).order_by('firstname')

class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Contact
    context_object_name = 'contact'
    template_name = 'contact/detail.html'

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        contact = self.get_object()
        if user != contact.user:
            raise PermissionDenied
        return super(DetailView, self).dispatch(request, *args, **kwargs)

    def get_object(self):
        return super().get_object()

class AddView(LoginRequiredMixin, generic.View):

    form = ContactForm
    address_form = AddressForm

    template = 'contact/add.html'

    def get(self, request):
        return render(request, self.template, {
            'form': self.form(),
            'address_form': self.address_form()
        })

    def post(self, request):
        form = self.form(request.POST)
        address_form = self.address_form(request.POST)
        if form.is_valid() and address_form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            address = address_form.save(commit=False)
            address.contact = contact
            address.save()
            return HttpResponseRedirect(reverse('contact:index'))

        return render(request, self.template, {
            'form': form(),
            'address_form': address_form()
        })

class SearchView(generic.View):
    def get(self, request):
        text = request.GET.get('text')
        contacts = Contact.objects.filter(Q(firstname__icontains=text) | Q(lastname__icontains=text)).order_by('firstname')
        rendered = render_to_string('contact/contact-list.html', {'contact_list': contacts})
        return JsonResponse({'data': rendered})

apps/front/views.py
from django.template.response import TemplateResponse

__author__ = 'snake'


def home(request):
    return TemplateResponse(request, 'home.html', {
    })


def error(request):
    return TemplateResponse(request, 'custom-404.html', {
    })

apps/contact/templates/contact/add.html
{% extends 'contact/base.html' %}

{% block title %}{{ block.super }} | Add a contact{% endblock %}

{% block content %}

    <form action="{% url 'contact:add_contact' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {{ address_form }}
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

apps/contact/templates/contact/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}Address book{% endblock %}</title>
  </head>
  <body>

    {% block content %}{% endblock %}

    {% block javascript %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock %}
  </body>
</html>

apps/contact/templates/contact/contact-list.html
{% load contact_extras %}

{% for contact in contact_list %}
    <li><a href="{% url 'contact:detail' contact.id %}">{{ contact.firstname|ucfirst }} {{ contact.lastname|ucfirst }}</a></li>
{% endfor %}

apps/contact/templates/contact/detail.html
{% extends 'contact/base.html' %}

{% load contact_extras %}

{% block content %}

    {{ contact.firstname|ucfirst }} {{ contact.lastname|ucfirst }}
    {{ contact.email }}
    {{ contact.phone }}
    {{ contact.address.street_name }}

{% endblock %}

apps/contact/templates/contact/index.html
{% extends 'contact/base.html' %}

{% load static %}

{% load i18n %}

{% block content %}

    <h1>{% trans 'Contacts' %} <a href="{% url 'contact:add_contact' %}">+</a></h1>

    <form id="search-contact-form" method="get", action="{% url 'contact:search' %}">
        <input type="text" name="text" id="search-input" placeholder="Search...">
    </form>

    {% if contact_list %}
        <ul id="contact-list">
            {% include "contact/contact-list.html" %}
        </ul>
    {% else %}
        <p>{% trans 'Aucun contact.' %}</p>
    {% endif %}

{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'contact/js/app.min.js' %}"></script>
{% endblock %}

apps/front/templates/_footer.html
{% load staticfiles i18n %}

<footer>
    <div class="container text-center">
        <a href="//nixa.ca" class="nixa-widget">
            <div class="nixa-logo">
                <img class="nixa-logo-img" src="{% static 'img/nixa.svg' %}" alt="">
            </div>
            <div class="nixa-text">{% trans 'Développement web par Nixa' %}</div>
        </a>
    </div>
</footer>

apps/front/templates/_header.html
{% load i18n %}

{% trans 'Header' %}

apps/front/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="{{ request.LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta property="og:image" content="{% static 'img/social-network.png' %}"/>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{% static 'css/main.css' %}" rel="stylesheet">
        {% block extra_css %}{% endblock %}
        <link rel="icon" href="{% static 'img/favicon.png' %}">
        <link rel="apple-touch-icon" href="{% static 'img/touch-icon.png' %}">
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body id="{% block bodyid %}{% endblock %}" ontouchstart="">
    {% block header %}
        {% include '_header.html' %}
    {% endblock %}
    {% block content %}{% endblock %}
    {% block footer %}
        {% include '_footer.html' %}
    {% endblock %}

    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block extra_js %}
        <script src="{% static 'js/app.min.js' %}"></script>
    {% endblock %}
	<!-- cache version {% now 'Y-m-d H:i:s' %} -->
    </body>
</html>

apps/front/templates/custom-404.html
{% extends 'base.html' %}
{% load i18n %}
{% block bodyid %}error404{% endblock %}
{% block title %}{% trans 'Page Introuvable' %}{% endblock %}
{% block content %}
{% trans 'Home' %}
<main id="page-404">
    <div class="vcenter-parent">
        <div class="vcenter-middle">
            <section id="404">
                <div class="container">
                    <h1>{% trans "Erreur 404" %}</h1>
                    <p class="pull-right">{% trans "La page demandée est introuvable." %}</p>
                    <button type="button" class="btn btn-default">{% trans "Retourner à l'accueil" %}</button>
                </div>
            </section>
        </div>
    </div>
</main>
{% endblock %}

apps/front/templates/email_templates/html/base.html
{% load staticfiles i18n front %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>{% block email_title %}{% endblock %} - {{ PROJECT_TITLE }}</title>
        <style type="text/css">
            {% include_static 'css/email.css' %}
        </style>

    </head>
    <body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;margin: 0;padding: 0;background-color: #E8EAEC;height: 100% !important;width: 100% !important;">
        <center>
            <table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;margin: 0;padding: 0;background-color: #E8EAEC;border-collapse: collapse !important;height: 100% !important;width: 100% !important;">
                <tr>
                    <td align="center" valign="top" id="bodyCell" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;margin: 0;padding: 20px;border-top: 10px solid {{ COLOR_BORDER_BODY }};border-bottom: 10px solid {{ COLOR_BORDER_BODY }};height: 100% !important;width: 100% !important;">
                        <!-- BEGIN TEMPLATE // -->
                        <table border="0" cellpadding="0" cellspacing="0" id="templateContainer" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;width: 600px;border-collapse: collapse !important;">
                            <tr>
                                <td align="center" valign="top" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                                    <!-- BEGIN HEADER // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateHeader" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;background-color: #fff;border-collapse: collapse !important;">
                                        <tr>
                                            <td valign="top" class="headerContent" width="100px" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;color: #505050;font-family: Helvetica;font-size: 20px;font-weight: bold;line-height: 100%;padding-top: 20px;padding-right: 30px;padding-bottom: 20px;padding-left: 30px;text-align: left;vertical-align: middle;border-top: 10px solid {{ COLOR_BORDER_HEADER }};">
                                                <a href="{{ PROJECT_URI }}" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;color: {{ COLOR_TEXT_LINKS }};font-weight: normal;text-decoration: underline;">
                                                    <img src="{{ PROJECT_URI }}{% static 'img/logo.png' %}" style="max-width: 600px;-ms-interpolation-mode: bicubic;border: 0;height: auto;line-height: 100%;outline: none;text-decoration: none;" alt="{{ PROJECT_TITLE }}" id="headerImage">
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- // END HEADER -->
                                </td>
                            </tr>
                            <tr>
                                <td align="center" valign="top" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                                    <!-- BEGIN HEADER // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateTitle" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;background-color: {{ COLOR_BG_HEADER }};border-collapse: collapse !important;">
                                        <tr>
                                            <td valign="top" class="headerTitle" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;padding-top: 30px;padding-right: 20px;padding-left: 30px;padding-bottom: 30px;">
                                                <h1 style="display: block;font-size: 22px;font-weight: bold;font-family: Helvetica;font-style: normal;line-height: 130%;letter-spacing: 1px;margin-top: 0;margin-right: 0;margin-bottom: 0;margin-left: 0;text-align: left;color: {{ COLOR_TEXT_HEADER }} !important;">{% block subject %}{% endblock %}</h1>
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- // END HEADER -->
                                </td>
                            </tr>
                            <tr>
                                <td align="center" valign="top" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                                    <!-- BEGIN BODY // -->
                                    {% block content %}{% endblock %}
                                    <!-- // END BODY -->
                                </td>
                            </tr>
                            <tr>
                                <td align="center" valign="top" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                                    <!-- BEGIN FOOTER // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateFooter" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;background-color: #171923;border-collapse: collapse !important;">
                                        <tr>
                                            <td valign="top" class="footerContent" width="58" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;color: {{ COLOR_TEXT_FOOTER }};font-family: Helvetica;font-size: 10px;line-height: 150%;padding-top: 20px;background-color: {{ COLOR_BG_FOOTER }};padding-right: 30px;padding-bottom: 20px;padding-left: 30px;text-align: left;">
                                                <a href="{{ PROJECT_URI }}" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;color: {{ COLOR_TEXT_LINKS }};font-weight: normal;text-decoration: underline;">
                                                    <img src="{{ PROJECT_URI }}{% static 'img/logo_email.png' %}" style="max-width: 600px;-ms-interpolation-mode: bicubic;border: 0;height: auto;line-height: 100%;outline: none;text-decoration: none;" id="headerImage">
                                                </a>
                                            </td>
                                            <td valign="middle" class="footerContent footerLinks" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;color: {{ COLOR_TEXT_FOOTER }};font-family: Helvetica;font-size: 10px;line-height: 150%;padding-top: 20px;background-color: {{ COLOR_BG_FOOTER }};padding-right: 30px;padding-bottom: 20px;padding-left: 0;text-align: left;">
                                                <strong>{{ PROJECT_TITLE }}</strong><br>
                                                <a href="{{ PROJECT_URI }}" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;color: {{ COLOR_TEXT_LINKS }};font-weight: normal;text-decoration: underline;">{{ PROJECT_URI }}</a><br>
                                                <a href="mailto:{{ PROJECT_CONTACT }}" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;color: {{ COLOR_TEXT_FOOTER }};font-weight: normal;text-decoration: none;">{{ PROJECT_CONTACT }}</a><br>
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- // END FOOTER -->
                                </td>
                            </tr>
                        </table>
                        <!-- // END TEMPLATE -->
                    </td>
                </tr>
            </table>
        </center>
    </body>
</html>

apps/front/templates/email_templates/html/contact_email.html
{% extends 'email_templates/html/base.html' %}
{% load i18n %}
{% block email_title %}{% trans 'Nouveau message' %}{% endblock %}
{% block subject %}{% trans 'Nouveau message' %}{% endblock %}

{% block content %}
    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateBody" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;background-color: #fff;border-collapse: collapse !important;">
        <tr>
            <td valign="top" class="bodyContent bodyMain" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;color: #18181a;font-family: Helvetica;font-size: 14px;line-height: 190%;padding-top: 30px;padding-right: 30px;padding-bottom: 30px;padding-left: 30px;text-align: left;">
                <strong>{% trans 'Nom' %}:</strong> {{ contact.name }}<br />
                <strong>{% trans 'Couriel' %}:</strong> {{ contact.email }}<br />
                {% if contact.phone %}<strong>{% trans 'Téléphone' %}:</strong> {{ contact.phone }}{% endif %}
            </td>
        </tr>
        <tr>
            <td align="center" valign="top" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                <!-- BEGIN BODY // -->
                <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateMessage" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;background-color: #F4F4F4;border-collapse: collapse !important;">
                    <tr>
                        <td valign="top" class="bodyContent bodyMain" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;color: #18181a;font-family: Helvetica;font-size: 14px;line-height: 190%;padding-top: 30px;padding-right: 30px;padding-bottom: 30px;padding-left: 30px;text-align: left;">
                            {% if contact.subject %}
                                <strong>{% trans 'Sujet' %}:</strong> {{ contact.subject }}<br/>
                            {% endif %}
                             <strong>{% trans 'Message' %}:</strong> {{ contact.message }}
                        </td>
                    </tr>
                </table>
                <!-- // END BODY -->
            </td>
        </tr>
    </table>
{% endblock %}

apps/front/templates/email_templates/html/new_account.html
{% extends 'email_templates/html/base.html' %}
{% load i18n %}
{% block email_title %}{% trans 'Nouveau message' %}{% endblock %}
{% block subject %}{% trans 'Nouveau message' %}{% endblock %}

{% block content %}
    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateBody" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;background-color: #fff;border-collapse: collapse !important;">
        <tr>
            <td align="center" valign="top" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                <!-- BEGIN BODY // -->
                <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateMessage" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;border-collapse: collapse !important;">
                    <tr>
                        <td valign="top" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;color: #18181a;font-family: Helvetica;font-size: 14px;line-height: 190%;padding-top: 30px;padding-right: 30px;padding-bottom: 60px;padding-left: 30px;text-align: left;">
                            <p style="font-size: 18px; font-weight: bold;">{% trans "Bienvenue" %} Albert Einstein,</p>
                            <p style="margin-bottom: 25px;">
                                {% trans "Grâce à votre nouveau compte, vous pourrez bénéficier de plusieurs avantages tels que " %}lorem ipsum dolor sit amet.
                            </p>
                            <a href="#" style="text-decoration: none; color: #fff; border: 10px solid #989898; background-color: #989898;" target="_blank" title="{% trans 'Aller sur le site web'%}">{% trans "Aller sur le site web" %}</a>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;color: #18181a;font-family: Helvetica;font-size: 14px;line-height: 190%;padding-right: 30px;padding-bottom: 50px;padding-left: 30px;text-align: left;">
                            <h2 style="font-size: 16px; margin-top: 0;">{% trans "Information du compte" %}</h2>
                            <p style="margin: 0;">
                                <strong>{% trans "Nom d'utlisateur" %}</strong>: AlbertEintein<br>
                                <strong>{% trans "Mot de passe" %}</strong>: N***********************e
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;color: #18181a;font-family: Helvetica;font-size: 14px;line-height: 190%;padding-right: 30px;padding-bottom: 50px;padding-left: 30px;text-align: left;">
                            <div style="padding: 20px; background-color: #f4f4f4;">
                                <p style="margin: 0;">{% trans "Vous avez des questions ou avez besoin de support?" %}<a href="#" target="_blank;" style="color: #5c19af; text-decoration: none;">{% trans "Contactez nous!" %}</a></p>
                            </div>
                        </td>
                    </tr>
                </table>
                <!-- // END BODY -->
            </td>
        </tr>
    </table>
{% endblock %}

apps/front/templates/email_templates/plain/contact_email.html
{% load i18n %}

{% trans 'Nom' %}: {{ contact.name }}
{% trans 'Couriel' %}: {{ contact.email }}
{% if contact.phone %}{% trans 'Téléphone' %}: {{ contact.phone }}{% endif %}
{% if contact.subject %}{% trans 'Sujet' %}: {{ contact.subject }}{% endif %}
{% trans 'Message' %}: {{ contact.message }}